#!/bin/bash

# Image Download Helper Script
# This script provides URLs to download curated stock photos for The Relocation Expo

echo "🎨 The Relocation Expo - Image Download Guide"
echo "=============================================="
echo ""
echo "Please download the following images manually from the URLs below:"
echo ""

echo "📸 HERO SECTION (Priority 1)"
echo "----------------------------"
echo "1. Expo Hall / Job Fair Crowd:"
echo "   - https://unsplash.com/s/photos/career-fair"
echo "   - https://unsplash.com/s/photos/job-expo"
echo "   - Search: 'networking event conference'"
echo "   - Save as: public/images/hero/expo-hall.jpg"
echo ""

echo "📸 WHY ATTEND SECTION (Priority 1)"
echo "-----------------------------------"
echo "2. Professional Consultation:"
echo "   - https://unsplash.com/s/photos/professional-meeting"
echo "   - https://unsplash.com/s/photos/career-counseling"
echo "   - Save as: public/images/sections/consultation.jpg"
echo ""

echo "📸 EXHIBITOR SECTION (Priority 1)"
echo "----------------------------------"
echo "3. Exhibition Booth:"
echo "   - https://unsplash.com/s/photos/exhibition-booth"
echo "   - https://unsplash.com/s/photos/trade-show"
echo "   - Save as: public/images/sections/exhibition-booth.jpg"
echo ""

echo "📸 TESTIMONIALS (Priority 2)"
echo "-----------------------------"
echo "4. Professional Headshots (3 needed):"
echo "   - https://unsplash.com/s/photos/professional-portrait"
echo "   - https://unsplash.com/s/photos/business-headshot"
echo "   - Save as: public/images/testimonials/person-1.jpg"
echo "   - Save as: public/images/testimonials/person-2.jpg"
echo "   - Save as: public/images/testimonials/person-3.jpg"
echo ""

echo "📸 WHO SHOULD ATTEND (Priority 2)"
echo "----------------------------------"
echo "5. Diverse Professionals:"
echo "   - https://unsplash.com/s/photos/young-professional"
echo "   - https://unsplash.com/s/photos/diverse-team"
echo "   - Save as: public/images/sections/professionals.jpg"
echo ""

echo "✅ AFTER DOWNLOADING:"
echo "--------------------"
echo "1. Place images in the correct public/images/ subdirectories"
echo "2. Run: npm run optimize-images (if available)"
echo "3. Update IMAGE_SOURCES.md with credits"
echo "4. Test the site: npm run dev"
echo ""

echo "💡 TIP: Look for images with:"
echo "   - Natural lighting"
echo "   - Diverse, professional people"
echo "   - European/Irish context when possible"
echo "   - Authentic, candid moments"
echo "   - High resolution (1920px+ width)"
echo ""

echo "🔗 QUICK LINKS:"
echo "--------------"
echo "Unsplash: https://unsplash.com"
echo "Pexels: https://pexels.com"
echo "Pixabay: https://pixabay.com"
echo ""
